services:

  stat-db:
    image: postgres:16.1
    container_name: pg-stats
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm

  user-db:
    image: postgres:16.1
    container_name: pg-users
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm

  event-db:
    image: postgres:16.1
    container_name: pg-event
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm

  request-db:
    image: postgres:16.1
    container_name: pg-request
    ports:
      - "6544:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm

  comment-db:
    image: postgres:16.1
    container_name: pg-comment
    ports:
      - "6545:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm