DROP TABLE IF EXISTS participation_requests;

CREATE TABLE IF NOT EXISTS participation_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id bigint NOT NULL,
    event_id bigint NOT NULL,
    status varchar NOT NULL,
    created_on timestamp NOT NULL
);