server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        # user-service routes
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**

        # request service routes
        - id: request-service-events-requests
          uri: lb://request-service
          predicates:
            - Path=/users/{userId}/events/{eventId}/requests/**

        - id: request-service-user-requests
          uri: lb://request-service
          predicates:
            - Path=/users/{userId}/requests/**

        # event-service routes
        - id: event-service-admin-categories
          uri: lb://event-service
          predicates:
            - Path=/admin/categories/**

        - id: event-service-categories
          uri: lb://event-service
          predicates:
            - Path=/categories/**

        - id: event-service-admin-compilations
          uri: lb://event-service
          predicates:
            - Path=/admin/compilations/**

        - id: event-service-compilations
          uri: lb://event-service
          predicates:
            - Path=/compilations/**

        - id: event-service-admin-events
          uri: lb://event-service
          predicates:
            - Path=/admin/events/**

        - id: event-service-events
          uri: lb://event-service
          predicates:
            - Path=/events/**

        - id: event-service-user-events
          uri: lb://event-service
          predicates:
            - Path=/users/{userId}/events/**

        # comment-service routes (feature)
        - id: comment-service-admin
          uri: lb://comment-service
          predicates:
            - Path=/admin/comments/**

        - id: comment-service-public
          uri: lb://comment-service
          predicates:
            - Path=/comments/**

        - id: comment-service-private
          uri: lb://comment-service
          predicates:
            - Path=/users/{userId}/comments

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      probes:
        enabled: true
    gateway:
      enabled: true
      access: "read-only"
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true

    instances:
      commonCircuitBreaker:
        baseConfig: default

  timelimiter:
    configs:
      default:
        timeoutDuration: 3s

    instances:
      commonCircuitBreaker:
        baseConfig: default