DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS compilations;
DROP TABLE IF EXISTS compilation_events;

CREATE TABLE IF NOT EXISTS categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id bigint NOT NULL,
    user_id bigint NOT NULL,
    title varchar(120) NOT NULL,
    annotation varchar(2000) NOT NULL,
    description varchar(7000) NOT NULL,
    event_date timestamp NOT NULL,
    location_lat float NOT NULL,
    location_lon float NOT NULL,
    paid boolean NOT NULL DEFAULT FALSE,
    participant_limit int NOT NULL DEFAULT 0,
    request_moderation boolean NOT NULL DEFAULT TRUE,
    state varchar(20) NOT NULL DEFAULT 'PENDING',
    created_on timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_on timestamp,
    confirmed_requests int NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(50) NOT NULL,
    pinned BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS compilation_events (
    compilation_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    PRIMARY KEY (compilation_id, event_id)
);