CREATE TABLE IF NOT EXISTS users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(254) NOT NULL UNIQUE,
    name varchar(250) NOT NULL
);

CREATE TABLE IF NOT EXISTS categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id bigint NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title varchar(120) NOT NULL,
    annotation varchar(2000) NOT NULL,
    description varchar(7000) NOT NULL,
    event_date timestamp NOT NULL,
    location_lat float NOT NULL,
    location_lon float NOT NULL,
    paid boolean NOT NULL DEFAULT FALSE,
    participant_limit int NOT NULL DEFAULT 0,
    request_moderation boolean NOT NULL DEFAULT TRUE,
    state varchar(20) NOT NULL DEFAULT 'PENDING',
    created_on timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_on timestamp,
    confirmed_requests int NOT NULL
);

CREATE TABLE IF NOT EXISTS participation_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id bigint NOT NULL REFERENCES users ON DELETE CASCADE,
    event_id bigint NOT NULL REFERENCES events ON DELETE CASCADE,
    status varchar NOT NULL,
    created_on timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(50) NOT NULL,
    pinned BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS compilation_events (
    compilation_id BIGINT NOT NULL REFERENCES compilations(id) ON DELETE CASCADE,
    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    PRIMARY KEY (compilation_id, event_id)
);

CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text TEXT NOT NULL,
    author_id BIGINT NOT NULL REFERENCES users ON DELETE CASCADE,
    event_id BIGINT NOT NULL REFERENCES events ON DELETE CASCADE,
    created_on timestamp NOT NULL,
    edited_on timestamp
);